### ISSUE TITLE
filter on a field for a set of values (OR between values) 

### ISSUE THREAD

**Issue by apelliciari** [alex/django-filter#137] opened 2014-02-16 11:52 UTC
Hi,

i don't know if is the right place to ask, because it's not an issue, just a question.

I'm using django-filter with Django-REST-Framework to build APIs for my app (great job by the way to both of you!)

I would like to know if there's a way to get this filter working 

`http://example.com/api/products?category=clothing,shoes`

to get all products with category "clothing" OR category "shoes".

I've tried with 

`http://example.com/api/products?category=clothing&category=shoes`

but as expected it does an AND between the filters and retrieve only the shoes products (i suppose because it's the last filter).

**Comment by TankOs** [comment] 2015-01-07 20:46
Just wanted to let you guys know that a change in django-filter requires an adjusted @ddevlin solution. ;-)

```python
from django_filters import Filter
from django_filters.fields import Lookup

class ListFilter( Filter ):
  def filter( self, qs, value ):
    return super( ListFilter, self ).filter( qs, Lookup( value.split( u"," ), "in") )
```

**Comment by tuky** [comment] 2015-02-23 11:05
i think, most people cannot use `MultipleChoiceFilter` directly, because they want to OR-filter on fields that are _not_ a `MultipleChoiceField`, e.g. `id`: `http://example.com/api/products?id=2&id=3`. Right now, this can only be done with the solution in https://github.com/alex/django-filter/issues/137#issuecomment-37820702

**Comment by kmwenja** [comment] 2015-03-06 17:46
Does @ddevlin solution work for any type of filter (ie Number, Char)?

**Comment by carltongibson** [comment] 2015-03-06 18:20
You might have to adjust types, but it should do (more or less)

**Comment by kmwenja** [comment] 2015-03-06 18:21
@carltongibson so does that mean inheriting from different filter types or actually typing the split values?

**Comment by carltongibson** [comment] 2015-03-06 19:27
Yeah, you'll have to implement the filter yourself (but it's only small). `split` will give you a list of strings, if you're filtering on, say, an `IntegerField` you'll need to covert the value.

**Comment by kmwenja** [comment] 2015-03-07 16:54
@carltongibson you were right, here's my implementation:

```
class ListFilter(CharFilter):

    def sanitize(self, value_list):
        """
        remove empty items in case of ?number=1,,2
        """
        return [v for v in value_list if v != u'']

    def customize(self, value):
        return value

    def filter(self, qs, value):
        multiple_vals = value.split(u",")
        multiple_vals = self.sanitize(multiple_vals)
        multiple_vals = map(self.customize, multiple_vals)
        actual_filter = django_filters.fields.Lookup(multiple_vals, 'in')
        return super(ListFilter, self).filter(qs, actual_filter)
```

So for filtering integers:

```
class ListIntegerFilter(ListFilter):

    def customize(self, value):
        return int(value)
```

**Comment by zoidbergwill** [comment] 2015-06-23 13:10
>(There's a separate issue about the ?a=1,2,3 syntax. That is on my list to come back to at a later date.)

Sorry to post this on this issue, but I really can't find the issue. @carltongibson . Is it closed?

**Comment by xordoquy** [comment] 2015-06-23 13:22
https://github.com/alex/django-filter/issues/137

**Comment by carltongibson** [comment] 2015-06-23 13:33
Hey @zoidbergwill — No problem — and "Not exactly". 

The are two options if you want to support the `1,2,3` syntax — a custom filter(as per the examples in this thread) or (I'm coming round to thinking) a custom widget that implements `value_from_datadict` to return the list you're after. 

(For this latter suggestion see my similar comment on [#187](https://github.com/alex/django-filter/issues/187#issuecomment-104551974))

If there's anything specific I'm happy for an issue on the `1,2,3` syntax to be opened — but I'm inclined to see it as a documentation issue — I'm very keen to encourage users to implement the project specific filters and widgets they need. 

(I **really** must sit down and give the docs the love they need.)

**Comment by zoidbergwill** [comment] 2015-06-24 11:58
I ended up using a custom simple [`CommaSeparatedValueFilter`](https://gist.github.com/zoidbergwill/9ea0e4feb62a45acffee) to get the behaviour I was looking for.

It's not a difficult filter to write, but for some reason I expected it to work out the box. I guess it is more of a documentation issue. 

While reading these docs and seeing how lists worked in the queries when using the `FilterSet` class directly in the tests, I thought it'd work, until I looked through the code properly.

**Comment by tiagoboldt** [comment] 2015-06-24 13:55
this is a recurring question and a requirement for many. I'm all in favor of having an implementation available in the framework.

**Comment by carltongibson** [comment] 2015-06-24 20:10
@tiagoboldt Are you talking about the Or filtering or the `1,2,3` syntax? 

The Or filtering works — this ticket is only still open because I haven't had the time to sit down and go over every corner of it to make sure there's nothing lurking.

As for supporting `1,2,3` query param syntax, I'll grant it needs documenting but a custom widget here is a simple thing. 

>  I'm all in favor of having an implementation available in the framework.

PRs welcome.

**Comment by tiagoboldt** [comment] 2015-06-24 20:41
@carltongibson 1,2,3 syntax. I've been using django-rest for some time and every project the need for such custom filter appears.

**Comment by visigoth** [comment] 2015-08-02 21:30
i just ran across this issue in a project i'm working on. i used some of the above code to come up with a similar solution that works across ManyToMany relationships. that is, i have a Blog model with entries=model.ManyToManyField(Entry). when i tried the code from @ddevlin and @kmwenja , i ran into the fact that Relationship fields do not support Lookup. however, you can use Q expressions to achieve the desired filter expression. Here's my replacement code:

```
class ListFilter(django_filters.Filter):
  def __init__(self, filter_value=lambda x: x, **kwargs):
    super(ListFilter, self).__init__(**kwargs)
    self.filter_value_fn = filter_value

  def sanitize(self, value_list):
    return [v for v in value_list if v != u'']

  def filter(self, qs, value):
    values = value.split(u",")
    values = self.sanitize(values)
    values = map(self.filter_value_fn, values)
    f = Q()
    for v in values:
      kwargs = {self.name: v}
      f = f|Q(**kwargs)
    return qs.filter(f)
```

In the FilterSet, i created a `ListFilter` with the relationship syntax, e.g. `entries = ListFilter(name='entries__id', filter_value=lambda x: int(x))`. I'm not too familiar with the innards of django_filters, but i oddly did not have to add it to the `fields` list in order to have my filter run.

**Comment by carltongibson** [comment] 2015-09-02 10:32
I'm going to close this as it's not a bug as it stands. We'll see if #259 makes sense for adding the `1,2,3` list syntax support as a custom widget but it should be easy enough to add in user land code if you need it in the meantime.

**Closed by carltongibson** 2015-09-02 10:32 UTC

**Comment by andybak** [comment] 2016-03-09 00:42
I'm a little confused as to why this is closed. Maybe it's a documentation issue but MultipleChoiceFilter doesn't seem to behave as expected as Tuky is states at https://github.com/carltongibson/django-filter/issues/137#issuecomment-75523719

I spent a good hour or so on this before I found this issue thread so at the very least the docs seem a nice big warning :-)

**Comment by carltongibson** [comment] 2016-03-09 06:58
What's the bug? Where's the failing test case demonstrating it? No one has been able to pin down the supposed issue.

**Comment by rohittk** [comment] 2016-03-30 08:07
I am sorry for asking, but what is that works now? for filtering things such as ?a=1,2,3

**Comment by tiagoboldt** [comment] 2016-03-30 10:01
From my understanding, it's:
`http://URL/something/?field=value1,value2,value3`
The expected query in django would be:
`something.objects.filter(Q(field=value1) | Q(field=value2) | Q(field=value3))`

**Comment by carltongibson** [comment] 2016-03-30 10:04
Yep. `?f=1&f=2&f=3` has always worked — it just requires the right widget. The new CSV stuff adds support for `?f=1,2,3` as a single value. 

Check the docs, have a play. Any issues open a new ticket.
