### ISSUE TITLE
Django 1.8 compatibility (continued)

### ISSUE THREAD

**Issue by melinath** [alex/django-filter#227] opened 2015-04-10 00:06 UTC
#224 fixed an AttributeError caused by changes to ForeignObjectRel objects, but that same error exists with ManyToOneRel objects.

```
  File "django-filter/django_filters/filterset.py", line 111, in filters_for_model
    field = get_model_field(model, f)
  File "django-filter/django_filters/filterset.py", line 90, in get_model_field
    model = rel.rel.to
AttributeError: 'ManyToOneRel' object has no attribute 'rel'
```

Model structure that causes this:

```
Model A
Model B
Model C
 - fk to A
 - fk to B
```

FilterSet is for A; filter field is c__b. If that makes sense?

**Comment by carltongibson** [comment] 2015-04-12 15:49
@melinath Fancy submitting a PR?

**Comment by melinath** [comment] 2015-04-14 02:20
Normally I would, but my time's pretty limited right now, and this isn't a blocking issue for us (yet).

**Comment by aRkadeFR** [comment] 2015-04-16 16:35
@carltongibson I see you merged into the develop branch the "fix get_model_field when using django 1.8. Is it possible to build and push to pypi?
thanks

**Comment by carltongibson** [comment] 2015-04-16 17:50
@aRkadeFR — Yeah sorry for the delay here: I've had zero capacity here. 

I will roll a new release just as soon as I can gather a few hours together to do it. In the meantime the best bet is to [get pip to install the branch](https://pip.pypa.io/en/latest/reference/pip_install.html#git) directly. You can revert to the PyPI release just as soon as it's made.

**Comment by frlinw** [comment] 2015-05-13 11:32
Exactly the same problem here with a beautiful 'ManyToOneRel' object has no attribute 'opts'
Sad :(

**Comment by carltongibson** [comment] 2015-05-13 12:56
Hello all — sorry to leave this hanging so long — what's (cough) "sad" is the general lack of time and/or pull requests here :-)

Anyhow — I'm looking to do a new release now. I'm going to close this since I can't reproduce. 

If you look in `tests/test_filterset.py:56` you can see the test added in #224. I've tried all sorts trying to trigger the `AttributeError` seen here. 

An example:

```
    def test_get_model_field_m2m(self):
        result = get_model_field(Book, 'lovers__username')
        self.assertEqual(result, User._meta.get_field('username'))
```

This passes. Again:

```
        result = get_model_field(Article, 'author__username')
```

... and so on...

What I can't see is what call to `get_model_field` triggers the exception. If someone can show me that I'm happy to re-open (and fix). 

----

Looking at the code I can't quite see how the `AttributeError` comes up anyway. The offending line is on the `else` branch of this: 

```
if isinstance(rel, ForeignObjectRel):
  # Fix from #224 applied here
else:
    # `AttributeError` raised here
```

But [`ManyToOneRel` is a subclass of `ForeignObjectRel`](https://github.com/django/django/blob/1.8/django/db/models/fields/related.py#L1402) — as are all the related fields — so how do we get here, ever?

As I say, totally happy to re-open but I need a reproduce.

**Closed by carltongibson** 2015-05-13 12:56 UTC

**Comment by melinath** [comment] 2015-11-11 00:31
Just checked on this again, still getting the same error on `0.11.0`

**Comment by melinath** [comment] 2015-11-11 00:31
I'll see if I can come up with a reproducible scenario for you in the next couple of days.

**Comment by melinath** [comment] 2015-11-11 00:34
Oooh, seems to be fixed on `develop`! Guess we'll just have to wait for the next release!

**Comment by melinath** [comment] 2015-11-11 00:40
FTR did a git bisect and the first working commit was 3d4a4e6ae282794f43846cb2c7a401cf25eac7a2.

**Comment by melinath** [comment] 2015-12-24 20:39
Any word on when the next release might be? I see that django-filter now works with 1.9, but I still don't have a release that works for me on 1.8 :-p

**Comment by zoidbergwill** [comment] 2015-12-24 20:56
Hi @melinath 

@carltongibson said he was planning on doing a release at the [beginning of January](https://github.com/alex/django-filter/pull/221#issuecomment-166843855).

**Comment by melinath** [comment] 2015-12-24 21:21
Great, thanks!
