### ISSUE TITLE
django1.7 AppRegistryNotReady

### ISSUE THREAD

**Issue by nsdont** [alex/django-filter#182] opened 2014-11-12 07:04 UTC
I use Sphinx build docs, raise error.
![image](https://cloud.githubusercontent.com/assets/1725434/5006409/1f1c1faa-6a7d-11e4-8f46-19d7530496f8.png)

**Comment by jaufrec** [comment] 2015-01-20 05:54
I had this issue migrating from 1.6 to 1.7 because I defined a filter in models.py.  I moved the filter class to a new filters.py and that solved the problem.

**Comment by joshuajonah** [comment] 2015-03-18 12:50
I moved the filter to a new file, but I'm still having this issue trying to use the filter in a view.

**Comment by carltongibson** [comment] 2015-03-18 13:20
I'm going to need something like a minimal reproduce case here. Preferably a failing test case. 

As described, it's hard to see what the issue could be: importing a model into a filters module and then importing the filter into a views module is the basic example set-up, it works — or A) there'd be more shouting and B) the project I have running in front of me now wouldn't work.

So the question is what are you doing differently? Currently there's not enough to be able to say. 

I'll leave this open for a few days to see if there's any more info but if not I'll close it as not-reproducible. (In this case we can always reopen if needed.)

**Closed** 2015-03-27 16:49 UTC
